// <auto-generated />
// This is a static replacement for the GitVersion-generated class.

[global::System.Runtime.CompilerServices.CompilerGenerated]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public static class GitVersionInformation
{
    public static string Major = "1";
    public static string Minor = "0";
    public static string Patch = "0";
    public static string PreReleaseTag = "";
    public static string PreReleaseTagWithDash = "";
    public static string PreReleaseLabel = "";
    public static string PreReleaseLabelWithDash = "";
    public static string PreReleaseNumber = "";
    public static string WeightedPreReleaseNumber = "";
    public static string BuildMetaData = "";
    public static string BuildMetaDataPadded = "";
    public static string FullBuildMetaData = "";
    public static string MajorMinorPatch = "1.0.0";
    public static string SemVer = "1.0.0";
    public static string LegacySemVer = "1.0.0";
    public static string LegacySemVerPadded = "1.0.0";
    public static string AssemblySemVer = "1.0.0.0";
    public static string AssemblySemFileVer = "1.0.0.0";
    public static string FullSemVer = "1.0.0";
    public static string InformationalVersion = "1.0.0.0";
    public static string BranchName = "unknown";
    public static string EscapedBranchName = "unknown";
    public static string Sha = "0000000000000000000000000000000000000000";
    public static string ShortSha = "0000000";
    public static string NuGetVersionV2 = "1.0.0";
    public static string NuGetVersion = "1.0.0";
    public static string NuGetPreReleaseTagV2 = "";
    public static string NuGetPreReleaseTag = "";
    public static string VersionSourceSha = "0000000000000000000000000000000000000000";
    public static string CommitsSinceVersionSource = "0";
    public static string CommitsSinceVersionSourcePadded = "0";
    public static string UncommittedChanges = "0";
    public static string CommitDate = "2026-08-03";
}